### ISSUE TITLE
Question: where to find definition of `glTexImage2D`?

### ISSUE THREAD

**Issue by gavrilikhin-d** [powervr-graphics/Native_SDK#90] opened 2024-08-05 12:17 UTC
There are some crashes that happen on devices inside of `glTexImage2D`, so we would like to investigate the source code of this method.

However, I can't seem to find definition of this function. Could you please give me a link?

**Comment by AlejandroCosin** [comment] 2024-08-05 13:10
Hi gavrilikhin-d,

thanks for reporting this issue. The source code of glTexImage2D is driver-dependent and implemented by each GPU manufacturer. You can report the information from the device where you are having this issue and we will try to reproduce and fix it.

We will need:
- Device name.
- GPU model.
- GPU driver version: On Linux, run command sudo cat /sys/kernel/debug/pvr/version and on Android, install Aida64 and follow instructions from https://forums.imgtec.com/t/vulkan-vkgetimagememoryrequirements2-crashes-on-powervr-8300/3458/4
- Operating System and version.
- SDK sample failing console log (logcat in the case of Android).

**Comment by gavrilikhin-d** [comment] 2024-08-05 13:37
Hi AlejandroCosim,

thank you for reaching out so fast and your help. The issue is probably on our site: we suspect that the error was caused by Java's buffer offset, which we forget to rewind and it could affect pointer's offset in C++ code.

Also we don't have access to the affected devices, but here is some info from Sentry:
<img width="845" alt="image" src="https://github.com/user-attachments/assets/c5eb8fd5-5fd0-4a68-97c2-e562000dddb2">
Device name: Xiaomi Redmi 9 
Model: M2006C3LII (QP1A.190711.020)
OS: Android 10 (QP1A.190711.020)
GPU model: PowerVR GE8320

**Comment by AlejandroCosin** [comment] 2024-08-05 14:15
Hi gavrilikhin-d,

Thanks for your message.

I hope you have good luck fixing the issue.

Since it seems it might be related with Java and the required information needed to work on this issue cannot be provided, I will be closing this issue. Please feel free to reopen it if the issue persists and you can provide the information requested (log / logcat, DDK, binaries, repro steps also would be needed).

Best regards,
Alejandro

**Closed by AlejandroCosin** 2024-08-05 14:15 UTC
Labels: feature request
